name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Make sure bytes.db is there
      - name: Verify database exists
        run: |
          ls -l bytes.db || (echo "Database file missing!" && exit 1)

      # Install Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Deploy to Railway
      - name: Deploy to Railway
        run: railway up --service production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
